<a href="https://colab.research.google.com/github/AhmadAlabrash/machine-learning/blob/main/Ro_numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np
import sys
import  time
import pprint

In [55]:
l1 = range(1000000)
l2 = range(1000000)


In [56]:
k1 = np.arange(1000000,dtype=int)
k2 = np.arange(1000000 ,dtype =int)

In [53]:
#time for make any calculas in list  is more than array 30 times (sometimes more)
start = time.time()
result = [(x+y ) for x,y in  zip(l1,l2)]
print((time.time()- start) *1000)


start = time.time()
res = k1+k2
print(1000 * ( time.time() -start))

137.54558563232422
4.517316818237305


In [57]:
# size of one item(ANY NUMBER) in list is : 28
# but of one item in array is : 4 for int    and   8 for float
print(sys.getsizeof(5))
print(k1.itemsize)

28
8


In [75]:
a1 =  np.array([[1,2,34,45,65],[1,2,34,45,65]] , dtype=int)
a2 = np.array([[1,2,34,45,65],[1,2,34,45,65]], dtype= np.float64)
print(a1.shape)
print(a1.reshape(5,2))
print(a1.itemsize)
print(a1.ndim)
print(a1.dtype)
print(a2.dtype)


(2, 5)
[[ 1  2]
 [34 45]
 [65  1]
 [ 2 34]
 [45 65]]
8
2
int64
float64


In [85]:
a3= np.zeros((3,66))
a4= np.ones((3,26))
print(a3)
print(a4)


print(a4.sum(axis=1))
print(np.count_nonzero( a4 ,axis=0))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]
[26. 26. 26.]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [88]:
a5 = np.array([[23,34,23,23,12,344],[233,678,9,87,67,3]])
a6 = np.array([[23,34,23,523,55412,344],[233,678,9,87,67,3]])

print(a5 + a6)
print(a5 - a6)
print(a5 * a6)
print(a5 / a6)

[[   46    68    46   546 55424   688]
 [  466  1356    18   174   134     6]]
[[     0      0      0   -500 -55400      0]
 [     0      0      0      0      0      0]]
[[   529   1156    529  12029 664944 118336]
 [ 54289 459684     81   7569   4489      9]]
[[1.00000000e+00 1.00000000e+00 1.00000000e+00 4.39770554e-02
  2.16559590e-04 1.00000000e+00]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00]]


In [115]:
print(np.vstack((a5,a6)))
print(np.hstack((a5,a6)))

print(np.hsplit(a5 , indices_or_sections=6))



[[   23    34    23    23    12   344]
 [  233   678     9    87    67     3]
 [   23    34    23   523 55412   344]
 [  233   678     9    87    67     3]]
[[   23    34    23    23    12   344    23    34    23   523 55412   344]
 [  233   678     9    87    67     3   233   678     9    87    67     3]]
[array([[ 23],
       [233]]), array([[ 34],
       [678]]), array([[23],
       [ 9]]), array([[23],
       [87]]), array([[12],
       [67]]), array([[344],
       [  3]])]


In [132]:
#to get rows

for row in a6 :
  print(row)

########################v################################



#to get columns

a7=np.array( [ [23,34,45,675,45],
                [12,43,54,554,665] ,
              [1342,4345,5564,5544,64653]    ] )

for i in range(len(a7[1])) :       
    for row in a7 :
      print(row[i])

########################################################



#to get all cells

for cell in a6.flat :
  print(cell)
  

[   23    34    23   523 55412   344]
[233 678   9  87  67   3]
23
12
1342
34
43
4345
45
54
5564
675
554
5544
45
665
64653
23
34
23
523
55412
344
233
678
9
87
67
3
